name: Build and release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.7.0"
          elixir-version: "1.18.0"
          rebar3-version: "3"
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: install js dependencies
        run: npm ci
      - name: build
        run: |
          gleam run -m build
          npx tailwindcss -i ./static/main.css -o ./priv/style.css
          echo "gearsco.de" > ./priv/CNAME
      - name: push to site branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: pages
          FOLDER: priv
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "{msg}"
